// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatingDemoTest;

namespace RatingDemoTest.Migrations
{
    [DbContext(typeof(RatingDemoContext))]
    partial class RatingDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RatingDemoTest.Domain.LoginServices", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsStillLogin")
                        .HasColumnType("bit");

                    b.Property<int>("LoginServiceId")
                        .HasColumnType("int");

                    b.Property<string>("LoginServicePassCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.ToTable("LoginServices");
                });

            modelBuilder.Entity("RatingDemoTest.Domain.ServicesRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RatedServiceComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatedServiceId")
                        .HasColumnType("int");

                    b.Property<int>("RatedServicePoint")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.ToTable("ServicesRating");
                });
#pragma warning restore 612, 618
        }
    }
}
